name: Testing library

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install AquesTalk1
        run: |
          cd ../
          wget https://www.a-quest.com/archive/package/aqtk1-lnx-eva_171.zip
          unzip aqtk1-lnx-eva_171.zip
          ls
      - name: Find cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build
      - name: Testing
        run: |
          LD_PRELOAD="../aqtk1-lnx-eva/lib64/m1/libAquesTalk.so" cargo run --example basic
