name: Testing library

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install AquesTalk1
        run: |
          wget https://www.a-quest.com/archive/package/aqtk1-lnx-eva_171.zip
          unzip aqtk1-lnx-eva_171.zip
          cp ./aqtk1-lnx-eva/lib32/dvd/libAquesTalk.so .
      - name: Testing
        run: LD_PRELOAD="./libAquesTalk.so" cargo run --example basic
